solar_parks_india = [
    "NP Kunta Ultra Mega Solar Park",
    "Kadapa Ultra Mega Solar Park",
    "Kurnool Ultra Mega Solar Park",
    "Ananthapuramu II Solar Park",
    "Pavagada Solar Park",
    "Rajnandgaon Solar Park",
    "Rewa Ultra Mega Solar",
    "Neemuch – Mandsaur Solar Park",
    "Agar – Shajapur Solar Park",
    "Paramount Solar Park (K.P. Power)",
    "Bhadla Solar Park",
    "Kamuthi Solar Power Project",
    "Gujarat Hybrid Renewable Energy Park",
    "Dholera Solar Park",
    "Gujarat Solar Park-1 (Charanka Solar Park)",
    "Radhanesda (Banaskantha) Solar Park",
    "Odisha Solar Park",
    "Charanka Solar Park",
    "Galiveedu Solar Park",
    "Mandsaur Solar Farm",
    "Ananthapuramu I Solar Park",
    "Hybrid Solar Wind Park",
    "Lohit Solar Park",
    "Harsad Solar Park",
    "Dholera Solar Park Phase I",
    "Dholera Solar Park Phase II",
    "Kaza Solar Park"
]
